/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6caee0bb-b09a-4484-a632-0bce51728563",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_cbXiE2jCZ",
    "aws_user_pools_web_client_id": "1rdd7oi9f6pn72abvv3sps3k9h",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "RemediationAPI",
            "endpoint": "https://imgj4b19wi.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "SoardinatorAPI",
            "endpoint": "https://7cpk5sylel.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "soardinator-remediation-cfns-221094580673",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
